### ISSUE TITLE
Fix header position

### ISSUE THREAD

**Issue by vtinev** [dimodimow/TableBook#2]
Wrap the content in a container.
```tsx
// layout.tsx
const Layout = () => {
  return (
    <div className="layout">
      <NavBar />
      <div className="mainContent">
        <Outlet />
      </div>
      <Footer />
    </div>
  );
};
```

Add padding to the first direct child (the one setting the background image).
```scss
// globals.scss
.mainContent > *:first-child {
  padding-top: 200px; // This will be changed according to resolutuion once you start doing responsive
}
```
